### ISSUE TITLE
Update to work with latest fabric loader version please :)

### ISSUE THREAD

**Issue by Sugar-Pink** [uItimatech/BetterFurniture#1]
Doesn't work with latest version of fabric loader 1.16

**Comment by uItimatech** [comment]
Just tested with fabric 1.16.0 and it worked perfectly fine for me. Do you have any other mods installed ?
Also make sure you have Fabric API version 0.100.7+1.21 installed (latest available).

**Comment by Sugar-Pink** [comment]
> Just tested with fabric 1.16.0 and it worked perfectly fine for me. Do you have any other mods installed ? Also make sure you have Fabric API version 0.100.7+1.21 installed (latest available).

Hi there so maybe I was wrong I mightve been running into other issues pertaining to my modpack, YES I have a lot of other mods installed haha. but this is what it says in my launcher when I load the pack. Not sure what it means

[ForkJoinPool-1-worker-9/WARN]:
 Mod betterfurniture uses the version fabric-1.21-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

I'm not sured if that meanst he mod can't work or not but I'll test it out rn.

**Comment by Sugar-Pink** [comment]
> Just tested with fabric 1.16.0 and it worked perfectly fine for me. Do you have any other mods installed ? Also make sure you have Fabric API version 0.100.7+1.21 installed (latest available).

Just tested it, it does work my apologies! I just saw you added yoru mod on modrinth and figured you'd appreciate it if I let you know (thinking it wasn't working) but i was wrong haha. BTW I love the simple yet charming design of the furniture. So many modders out there wander too far from minecrafts aesthetic and I hate that, but your mod looks lovely and fits right in with MC. Thanks. c:

**Comment by uItimatech** [comment]
Glad it now works and that you enjoy the mod !
I'm still going to push a minor update in case the semantics cause any incompatibility with whatever mod. Thanks for letting me know.
