### ISSUE TITLE
1.21 still uses pre-1.20.5 file directory formating. (still uses plurals instead of singles)

### ISSUE THREAD

**Issue by Ynaught** [uItimatech/BetterFurniture#2]
With version. . . I "think" 1.20.6(?), alot of the file directories have been changed from plural to singular.

Here's a small example:
- structures -> structure
- advancements -> advancement
- recipes -> recipe
- loot_tables -> loot_table
- predicates -> predicate
- item_modifiers -> item_modifier
- functions -> function
- tags/functions -> tags/function
- tags/items -> tags/item
- tags/blocks -> tags/block
- tags/entity_types -> tags/entity_type
- tags/fluids -> tags/fluid
- tags/game_events -> tags/game_event

This is not all of the changes, just a few. The file directories need to be updated in order for them to function in 1.21. Otherwise "recipes" as an example won't even have any recipe work/will behave as if the recipe is not even in the game at all. In addition to the other things I don't have quick access to that they changed, some keys were changed in the json files as well.

**Comment by uItimatech** [comment]
Oh yeah I completely forgot about that reformatting despite having prepare everything for it...
My bad, will be fixed asap.

**Comment by uItimatech** [comment]
Issue fixed, uploading update 1.0.4 to modrinth and curseforge. Thanks for your help.
